server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization?serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      
logging:
  level:
    org:
      hibernate:
        type: trace
        
   